### ISSUE TITLE
Run failed on Python 3.12

### ISSUE THREAD

**Issue by cybaol** [termux/termux-language-server#17]
![Screenshot_select-area_20240518170657](https://github.com/termux/termux-language-server/assets/48387783/4e205d2b-bc50-4a97-8318-8e9489855f63)

**Comment by Freed-Wu** [comment]
Upstream bug: https://github.com/grantjenks/py-tree-sitter-languages/issues/64

Wait https://github.com/grantjenks/py-tree-sitter-languages/pull/65

**Comment by ObserverOfTime** [comment]
Just use tree-sitter-bash directly.
