### ISSUE TITLE
[PKGBUILD] Error with element of variable "arch"

### ISSUE THREAD

**Issue by Spixmaster** [termux/termux-language-server#4]
The following line `arch=("x86_64")` in my PKGBUILD creates the error `'"x86_64"' is not one of ['any', 'i686', 'x86_64', 'arm', 'aarch64']`.

There is no correct handling of the double quotes.

**Comment by Freed-Wu** [comment]
I'll take a look.

**Comment by Freed-Wu** [comment]
Can you try the latest version? I think it can fix this bug.

```sh
pip install git+https://github.com/termux/termux-language-server
```

**Comment by Spixmaster** [comment]
I tried it and it seems to work. Thank you very much!
